config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :artist_badges

  resources :galleries do
  member do
    get "vote"
  end
end

  resources :styles

  resources :techniques

  resources :studios

  resources :artists

  resources :placements

  resources :user_badges

  resources :projects

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :studio
  has_many :techniques
  has_many :styles
  has_many :galleries
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :techniques
  has_and_belongs_to_many :styles
  has_many :artist_badges
end

app/models/artist_badge.rb
class ArtistBadge < ActiveRecord::Base
  belongs_to :artist
end

app/models/artist_badges.rb
class ArtistBadges < ActiveRecord::Base
  belongs_to :artist
  validates_formatting_of :badge_image, using: :url
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :artist
  belongs_to :project
  has_one :placement
  has_one :technique
  has_many :styles
  has_and_belongs_to_many :techniques
  has_and_belongs_to_many :styles
  has_and_belongs_to_many :placements
  has_and_belongs_to_many :projects
  validates_formatting_of :image, using: :url
  acts_as_votable 
end

app/models/placement.rb
class Placement < ActiveRecord::Base
  belongs_to :project
  has_and_belongs_to_many :galleries
  has_and_belongs_to_many :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_one :placement
  has_many :artists
  has_many :galleries
  has_and_belongs_to_many :placements
  has_and_belongs_to_many :artists
end

app/models/studio.rb
class Studio < ActiveRecord::Base
  validates_formatting_of :website, using: :url
  validates_formatting_of :email, using: :email
end

app/models/style.rb
class Style < ActiveRecord::Base
  belongs_to :artist
  has_and_belongs_to_many :artists
  has_and_belongs_to_many :galleries
end

app/models/technique.rb
class Technique < ActiveRecord::Base
  belongs_to :artist
  has_and_belongs_to_many :artists
  has_and_belongs_to_many :galleries
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  has_many :projects
  has_and_belongs_to_many :user_badges
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # Check if the User is already registered without Facebook
    user = User.where(email: auth.info.email).first

    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
end

app/models/user_badges.rb
class UserBadges < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates_formatting_of :badge_image, using: :url
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  before_action :set_technique, only: [:show, :edit, :update, :destroy]

  # GET /techniques
  # GET /techniques.json
  def index
    @techniques = Technique.all
  end

  # GET /techniques/1
  # GET /techniques/1.json
  def show
  end

  # GET /techniques/new
  def new
    @technique = Technique.new
  end

  # GET /techniques/1/edit
  def edit
  end

  # POST /techniques
  # POST /techniques.json
  def create
    @technique = Technique.new(technique_params)

    respond_to do |format|
      if @technique.save
        format.html { redirect_to @technique, notice: 'Technique was successfully created.' }
        format.json { render :show, status: :created, location: @technique }
      else
        format.html { render :new }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /techniques/1
  # PATCH/PUT /techniques/1.json
  def update
    respond_to do |format|
      if @technique.update(technique_params)
        format.html { redirect_to @technique, notice: 'Technique was successfully updated.' }
        format.json { render :show, status: :ok, location: @technique }
      else
        format.html { render :edit }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /techniques/1
  # DELETE /techniques/1.json
  def destroy
    @technique.destroy
    respond_to do |format|
      format.html { redirect_to techniques_url, notice: 'Technique was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technique
      @technique = Technique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technique_params
      params.require(:technique).permit(:name, :description, :artist_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/placements_helper.rb
module PlacementsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/studios_helper.rb
module StudiosHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/helpers/user_badges_helper.rb
module UserBadgesHelper
end

app/views/techniques/_form.html.erb
<%= form_for @technique, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  techniques_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/techniques/edit.html.erb
<%- model_class = Technique -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Technique %></h1>
</div>
<%= render :partial => 'form' %>

app/views/techniques/index.html.erb
<%- model_class = Technique -%>
<div class="page-header">
  <h1><%=t '.title', :default => Technique %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @techniques.each do |technique| %>
      <tr>
        <td><%= technique.id %></td>
        <td><%= technique.name %></td>
        <td><%= technique.description %></td>
        <td><%=l technique.created_at, format: :long %></td>
        <td>
          <%= link_to technique_path(technique), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to technique_path(technique), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_technique_path,
            :class => 'btn btn-primary' %>

app/views/techniques/new.html.erb
<%- model_class = Technique -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Technique %></h1>
</div>
<%= render :partial => 'form' %>

app/views/techniques/show.html.erb
<%- model_class = Technique -%>
<div class="page-header">
  <h1><%=t '.title', :default => Technique %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @technique.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @technique.description %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              techniques_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_technique_path(@technique), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              technique_path(@technique),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>